name: Build Beta Package

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Include version number
        run: echo "BETA-${{ github.run_number }}" > version.txt
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: thehaps
          SENTRY_PROJECT: beta
        with:
          tagName: BETA-${{ github.run_number }}
          environment: BETA
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: the-haps/libertas/libertas
          tags: beta, BETA-${{ github.run_number }}
