name: Build Release Package

on: [push]

jobs:
  push_to_registry:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: the-haps/libertas/libertas
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: latest
